export const INPUT_CHANGE = "INPUT_CHANGE";
export const POKEMON_LIST_UPDATE = "POKEMON_LIST_UPDATE";
export const CLEAR_INPUT = "CLEAR_INPUT";
export const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";
