export const INPUT_CHANGE = "INPUT_CHANGE";
export const POKEMON_LIST_UPDATE = "POKEMON_LIST_UPDATE";
export const CLEAR_INPUT = "CLEAR_INPUT";
export const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";
export const SET_FILTER_SECTION_VISIBILITY = "SET_FILTER_SECTION_VISIBILITY";
export const WEIGHT_CHANGE = "WEIGHT_CHANGE";
export const HEIGHT_CHANGE = "HEIGHT_CHANGE";
export const TYPE_CHANGE = "TYPE_CHANGE";
export const LIMIT_CHANGE = "LIMIT_CHANGE";
export const POKEMON_LIST_DATA_UPDATE = "POKEMON_LIST_DATA_UPDATE";
export const POKEMON_FILTERED_LIST_DATA_UPDATE =
  "POKEMON_FILTERED_LIST_DATA_UPDATE";
export const FILTERS_CHANGE = "FILTERS_CHANGE";
export const DISPLAY_MODE_UPDATE = "DISPLAY_MODE_UPDATE";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const UPDATE_AUTOCOMPLETE_LIST = "UPDATE_AUTOCOMPLETE_LIST";
export const SEARCH_POKEMON = "SEARCH_POKEMON";
export const RETURN_BUTTON_CLICK = "RETURN_BUTTON_CLICK";
